export { default as AuthRouter } from './auth'
export { default as ThreadRouter } from './thread'
export { default as QuestionRouter } from './question'
export { default as CommentRouter } from './comment'
export { default as QueryRouter } from './queries'